env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
  - react
rules:
  '@typescript-eslint/consistent-type-imports': 'error'
  'react/function-component-definition': off
  'react/jsx-uses-react': off
  'react/react-in-jsx-scope': off
  'react/require-default-props': off
